server:
  port: 8080
  servlet:
    context-path: /campsite-service

spring.datasource.url: jdbc:mysql://localhost:3306/campsite_booking?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC

# Username and password
spring.datasource.username: root
spring.datasource.password: root

# Keep the connection alive if idle for a long time
#spring.datasource.testWhileIdle: true
#spring.datasource.validationQuery: SELECT 1

#spring.jpa.show-sql: true
#logging.level.org.hibernate.type: TRACE

#spring.jpa.properties.hibernate.format_sql: true
#spring.jpa.properties.hibernate.show_sql: true
#spring.jpa.properties.hibernate.type: trace

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.javax.persistence.schema-generation.create-source: metadata
spring.jpa.properties.javax.persistence.schema-generation.scripts.action: drop-and-create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: db-create.sql
spring.jpa.properties.javax.persistence.schema-generation.scripts.drop-target: db-drop.sql